/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AuthRouteImport } from "./routes/auth"
import { Route as TabsRouteImport } from "./routes/_tabs"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TabsNotificationsRouteImport } from "./routes/_tabs.notifications"
import { Route as TabsInventoryRouteImport } from "./routes/_tabs.inventory"
import { Route as TabsEquipmentRouteImport } from "./routes/_tabs.equipment"
import { Route as TabsEarningsRouteImport } from "./routes/_tabs.earnings"
import { Route as TabsDashboardRouteImport } from "./routes/_tabs.dashboard"
import { Route as TabsContractsRouteImport } from "./routes/_tabs.contracts"
import { Route as TabsBookingsRouteImport } from "./routes/_tabs.bookings"
import { Route as TabsAccountRouteImport } from "./routes/_tabs.account"
import { Route as TabsEquipmentIdRouteImport } from "./routes/_tabs.equipment.$id"
import { Route as TabsBookingsNewRouteImport } from "./routes/_tabs.bookings.new"

const AuthRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: "/_tabs",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TabsNotificationsRoute = TabsNotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => TabsRoute,
} as any)
const TabsInventoryRoute = TabsInventoryRouteImport.update({
  id: "/inventory",
  path: "/inventory",
  getParentRoute: () => TabsRoute,
} as any)
const TabsEquipmentRoute = TabsEquipmentRouteImport.update({
  id: "/equipment",
  path: "/equipment",
  getParentRoute: () => TabsRoute,
} as any)
const TabsEarningsRoute = TabsEarningsRouteImport.update({
  id: "/earnings",
  path: "/earnings",
  getParentRoute: () => TabsRoute,
} as any)
const TabsDashboardRoute = TabsDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => TabsRoute,
} as any)
const TabsContractsRoute = TabsContractsRouteImport.update({
  id: "/contracts",
  path: "/contracts",
  getParentRoute: () => TabsRoute,
} as any)
const TabsBookingsRoute = TabsBookingsRouteImport.update({
  id: "/bookings",
  path: "/bookings",
  getParentRoute: () => TabsRoute,
} as any)
const TabsAccountRoute = TabsAccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => TabsRoute,
} as any)
const TabsEquipmentIdRoute = TabsEquipmentIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => TabsEquipmentRoute,
} as any)
const TabsBookingsNewRoute = TabsBookingsNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => TabsBookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/auth": typeof AuthRoute
  "/account": typeof TabsAccountRoute
  "/bookings": typeof TabsBookingsRouteWithChildren
  "/contracts": typeof TabsContractsRoute
  "/dashboard": typeof TabsDashboardRoute
  "/earnings": typeof TabsEarningsRoute
  "/equipment": typeof TabsEquipmentRouteWithChildren
  "/inventory": typeof TabsInventoryRoute
  "/notifications": typeof TabsNotificationsRoute
  "/bookings/new": typeof TabsBookingsNewRoute
  "/equipment/$id": typeof TabsEquipmentIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/auth": typeof AuthRoute
  "/account": typeof TabsAccountRoute
  "/bookings": typeof TabsBookingsRouteWithChildren
  "/contracts": typeof TabsContractsRoute
  "/dashboard": typeof TabsDashboardRoute
  "/earnings": typeof TabsEarningsRoute
  "/equipment": typeof TabsEquipmentRouteWithChildren
  "/inventory": typeof TabsInventoryRoute
  "/notifications": typeof TabsNotificationsRoute
  "/bookings/new": typeof TabsBookingsNewRoute
  "/equipment/$id": typeof TabsEquipmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_tabs": typeof TabsRouteWithChildren
  "/auth": typeof AuthRoute
  "/_tabs/account": typeof TabsAccountRoute
  "/_tabs/bookings": typeof TabsBookingsRouteWithChildren
  "/_tabs/contracts": typeof TabsContractsRoute
  "/_tabs/dashboard": typeof TabsDashboardRoute
  "/_tabs/earnings": typeof TabsEarningsRoute
  "/_tabs/equipment": typeof TabsEquipmentRouteWithChildren
  "/_tabs/inventory": typeof TabsInventoryRoute
  "/_tabs/notifications": typeof TabsNotificationsRoute
  "/_tabs/bookings/new": typeof TabsBookingsNewRoute
  "/_tabs/equipment/$id": typeof TabsEquipmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/auth"
    | "/account"
    | "/bookings"
    | "/contracts"
    | "/dashboard"
    | "/earnings"
    | "/equipment"
    | "/inventory"
    | "/notifications"
    | "/bookings/new"
    | "/equipment/$id"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/auth"
    | "/account"
    | "/bookings"
    | "/contracts"
    | "/dashboard"
    | "/earnings"
    | "/equipment"
    | "/inventory"
    | "/notifications"
    | "/bookings/new"
    | "/equipment/$id"
  id:
    | "__root__"
    | "/"
    | "/_tabs"
    | "/auth"
    | "/_tabs/account"
    | "/_tabs/bookings"
    | "/_tabs/contracts"
    | "/_tabs/dashboard"
    | "/_tabs/earnings"
    | "/_tabs/equipment"
    | "/_tabs/inventory"
    | "/_tabs/notifications"
    | "/_tabs/bookings/new"
    | "/_tabs/equipment/$id"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/auth": {
      id: "/auth"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_tabs": {
      id: "/_tabs"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_tabs/notifications": {
      id: "/_tabs/notifications"
      path: "/notifications"
      fullPath: "/notifications"
      preLoaderRoute: typeof TabsNotificationsRouteImport
      parentRoute: typeof TabsRoute
    }
    "/_tabs/inventory": {
      id: "/_tabs/inventory"
      path: "/inventory"
      fullPath: "/inventory"
      preLoaderRoute: typeof TabsInventoryRouteImport
      parentRoute: typeof TabsRoute
    }
    "/_tabs/equipment": {
      id: "/_tabs/equipment"
      path: "/equipment"
      fullPath: "/equipment"
      preLoaderRoute: typeof TabsEquipmentRouteImport
      parentRoute: typeof TabsRoute
    }
    "/_tabs/earnings": {
      id: "/_tabs/earnings"
      path: "/earnings"
      fullPath: "/earnings"
      preLoaderRoute: typeof TabsEarningsRouteImport
      parentRoute: typeof TabsRoute
    }
    "/_tabs/dashboard": {
      id: "/_tabs/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof TabsDashboardRouteImport
      parentRoute: typeof TabsRoute
    }
    "/_tabs/contracts": {
      id: "/_tabs/contracts"
      path: "/contracts"
      fullPath: "/contracts"
      preLoaderRoute: typeof TabsContractsRouteImport
      parentRoute: typeof TabsRoute
    }
    "/_tabs/bookings": {
      id: "/_tabs/bookings"
      path: "/bookings"
      fullPath: "/bookings"
      preLoaderRoute: typeof TabsBookingsRouteImport
      parentRoute: typeof TabsRoute
    }
    "/_tabs/account": {
      id: "/_tabs/account"
      path: "/account"
      fullPath: "/account"
      preLoaderRoute: typeof TabsAccountRouteImport
      parentRoute: typeof TabsRoute
    }
    "/_tabs/equipment/$id": {
      id: "/_tabs/equipment/$id"
      path: "/$id"
      fullPath: "/equipment/$id"
      preLoaderRoute: typeof TabsEquipmentIdRouteImport
      parentRoute: typeof TabsEquipmentRoute
    }
    "/_tabs/bookings/new": {
      id: "/_tabs/bookings/new"
      path: "/new"
      fullPath: "/bookings/new"
      preLoaderRoute: typeof TabsBookingsNewRouteImport
      parentRoute: typeof TabsBookingsRoute
    }
  }
}

interface TabsBookingsRouteChildren {
  TabsBookingsNewRoute: typeof TabsBookingsNewRoute
}

const TabsBookingsRouteChildren: TabsBookingsRouteChildren = {
  TabsBookingsNewRoute: TabsBookingsNewRoute,
}

const TabsBookingsRouteWithChildren = TabsBookingsRoute._addFileChildren(
  TabsBookingsRouteChildren,
)

interface TabsEquipmentRouteChildren {
  TabsEquipmentIdRoute: typeof TabsEquipmentIdRoute
}

const TabsEquipmentRouteChildren: TabsEquipmentRouteChildren = {
  TabsEquipmentIdRoute: TabsEquipmentIdRoute,
}

const TabsEquipmentRouteWithChildren = TabsEquipmentRoute._addFileChildren(
  TabsEquipmentRouteChildren,
)

interface TabsRouteChildren {
  TabsAccountRoute: typeof TabsAccountRoute
  TabsBookingsRoute: typeof TabsBookingsRouteWithChildren
  TabsContractsRoute: typeof TabsContractsRoute
  TabsDashboardRoute: typeof TabsDashboardRoute
  TabsEarningsRoute: typeof TabsEarningsRoute
  TabsEquipmentRoute: typeof TabsEquipmentRouteWithChildren
  TabsInventoryRoute: typeof TabsInventoryRoute
  TabsNotificationsRoute: typeof TabsNotificationsRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAccountRoute: TabsAccountRoute,
  TabsBookingsRoute: TabsBookingsRouteWithChildren,
  TabsContractsRoute: TabsContractsRoute,
  TabsDashboardRoute: TabsDashboardRoute,
  TabsEarningsRoute: TabsEarningsRoute,
  TabsEquipmentRoute: TabsEquipmentRouteWithChildren,
  TabsInventoryRoute: TabsInventoryRoute,
  TabsNotificationsRoute: TabsNotificationsRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
